[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read-write", path = "./deployments" }]
remappings = [
    "@reflex/=src/",
    "@cryptoalgebra/=lib/Algebra/",
    "@cryptoalgebra/core/=lib/Algebra/src/core/contracts/",
    "@cryptoalgebra/integral-core/contracts/=lib/Algebra/src/core/contracts/",
    "@cryptoalgebra/periphery/=lib/Algebra/src/periphery/contracts/",
    "@cryptoalgebra/plugin/=lib/Algebra/src/plugin/contracts/",
    "@cryptoalgebra/tokenomics/=lib/Algebra/src/tokenomics/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[lint]
lint_on_build = false


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
